### ISSUE TITLE
非常感谢大佬！小白有个小问题请教

### ISSUE THREAD

**Issue by tergarsam** [chika0801/sing-box-install#13]
在大佬教程中，端口指定为16384，密码为chika，如果想修改，该如何操作？

谢谢大佬！

**Comment by chika0801** [comment]
修改 /root/sing-box_config.json 这个文件，这是服务端配置文件，至于你在SSH里打命令，还是用其它软件如winscp都个人习惯。

改完记得保存并用systemctl restart sing-box，重启后才生效。

然后记得在你用的客户端程序GUI填端口，密码之类的对应处，做相应修改。

**Comment by tergarsam** [comment]
非常感谢大佬！这个脚本太好用了！

**Comment by chika0801** [comment]
不客气，这不是脚本，就是几步，手动复制粘贴 ，没技术的。

**Comment by chika0801** [comment]
你用的什么配置组合？比如你发下你的服务端配置文件？

**Comment by tgssaa** [comment]
在/root/sing-box_config.json中显示的是：
404: Not Found

**Comment by tgssaa** [comment]
另外，请问大佬，是否可以用CF的15年证书？如果能使用的话，在服务端和客户端设置，需要有什么不同吗？谢谢大佬！！

**Comment by chika0801** [comment]
> 另外，请问大佬，是否可以用CF的15年证书？如果能使用的话，在服务端和客户端设置，需要有什么不同吗？谢谢大佬！！

证书的话，我没用过CF的15年，不知道它是属于自签证书吗？建议你自己申请就是了。申请教程在这有的 https://github.com/chika0801/Xray-install

**Comment by chika0801** [comment]
> 在/root/sing-box_config.json中显示的是： 404: Not Found

光看这信息我帮不了你，你要不重装搭一次，或找台VPS重装系统后开始。sing-box的示例区我已经全更新过了。

**Comment by tgssaa** [comment]
好滴！谢谢大佬，我再试试看啊！
