### ISSUE TITLE
求一个grpc example

### ISSUE THREAD

**Issue by jh0072110** [chika0801/sing-box-install#2]
大佬可以写一个grpc的example么，我根据您之前的ws+nginx改了一下无法成功啊…水平菜了菜了……

**Comment by chika0801** [comment]
不能。因为我试过没成功。才想起来可能原因是https://github.com/SagerNet/sing-box/releases这里下载的版本，不带grpc模块，要用Grpc得去看文档自己编译，我反正不用grpc就算了。

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-examples/tree/main/VMess

且支持CF的CDN，如果gRPC要过，去CF网页要把gRPC开一下，默认没开。
