### ISSUE TITLE
openwrt下插件 SSR PLUS 如何设置 TROJAN客户端

### ISSUE THREAD

**Issue by isaac574** [chika0801/sing-box-install#4]
你好，大佬，

![image](https://user-images.githubusercontent.com/59785107/201371685-de742daf-be62-4f24-8b24-edb16e366e03.png)
只能这些一个也不选，时断时好。
不何为何？
服务器的JSON配置参见您的样本，只改了密码+端口。
盼赐教！
感谢！

**Comment by chika0801** [comment]
假设你服务器用的我的这个配置
https://github.com/chika0801/sing-box-install/blob/main/Trojan-TCP-TLS/config_server.json

端口16386，密码chika，地址填你VPS的IP，把TLS勾上，我记得会多出2个选项，有一个就是填SNI的地方（SSRP里面选项名字我现在忘记了，填你域名即可）

你图片上TLS没勾，肯定不通。

如果你的域名解析到你VPS的IP的，你就地址填域名 TLS勾上后多出来的选项不填也行。
