### ISSUE TITLE
我试着改写客户端这样的CONFIG.JSON

### ISSUE THREAD

**Issue by isaac574** [chika0801/sing-box-install#5]
{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 10808,
    "remote_addr": "example.com",
    "remote_port": 17386,
    "password": [
        "XXXXXX"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}

***您好，我试着改写客户端这样的CONFIG.JSON
在DEEPIN LINUX系统下 运行TROJAN客户端，显示找不到证书。
不知   "cert": "",    此处如何填写？
要从VPS上 下载证书到本地吗？

盼赐教。
感谢！！！

**Comment by chika0801** [comment]
你直接在linxux系统下用，我没用linxux系统不知道

我想你直接用Sing-box 程序 加客户端配置启动也行

或其它客户端trojan的配置我也没看过学过。
