### ISSUE TITLE
chika大佬

### ISSUE THREAD

**Issue by rianjskis** [chika0801/sing-box-install#7]
大佬,能不能还跟以前的xray配置一样，在示例中把dns跟跟出入站规则啥的加上,最近受您的影响,也转到sing-box了,用的hy协议+vless.可惜弄不好这个DNS跟出入站规则方面,从xray开始一直以来都是抄的您的配置哈哈哈,太菜了我, 另外用sing-box使用hy跟vless协议,不用nginx反代吗,看您这都没有,哈哈哈,麻烦您了.

**Comment by chika0801** [comment]
我认为现在能用的协议组合，TCP类就只有xray的vision，UDP类是hy和tuic。

上面的几种，我现在也都不配回落了（比如VISION可配）。HY和TUIC也没这功能，你不用再想着回落了。

你问DNS部分你把问题说详细点，我才能回答了。我在模块里放了些NF流量转发的示例。

你要说清楚你问的，我才能继续回答你。

**Comment by chika0801** [comment]
{
    "inbounds": [
        {
            "type": "hysteria",
            "tag": "hysteria-in",
            "listen": "::",
            "listen_port": 16384,
            "sniff": true,
            "sniff_override_destination": true,
            "domain_strategy": "prefer_ipv6",
            "up_mbps": 1000,
            "down_mbps": 1000,
            "users": [
                {
                    "auth_str": "chika"
                }
            ],
            "recv_window_conn": 33554432,
            "recv_window_client": 134217728,
            "max_conn_client": 4096,
            "disable_mtu_discovery": false,
            "tls": {
                "enabled": true,
                "alpn": [
                    "h3"
                ],
                "certificate_path": "/root/fullchain.cer",
                "key_path": "/root/private.key"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
        },
        "rules": [
            {
                "geoip": [
                    "cn"
                ],
                "outbound": "block"
            }
        ]
    }
}

**Comment by rianjskis** [comment]
您好大佬，抄写您的配置,我使用您教程的v2ray使用此配置无法ping通,没有反应,后来我使用https://github.com/SagerNet/sing-box/releases/download/v1.1-rc1/sing-box-1.1-rc1-linux-amd64.tar.gz 在本地运行得出一个decode config: json: unknown field "protocol" 解码配置：json：未知字段 "协议"   请教我是哪里出了问题呀,服务端运行没有问题,我看了下是正常的.
  <details><summary>服务端配置如下</summary> 

  ```
{
    "log": {
    "disabled": false,
    "level": "info",
    "output": "/root/sing-box/sing-box.log",
    "timestamp": true
 },
    "inbounds": [
        {
            "type": "hysteria",
            "tag": "hysteria-in",
            "listen": "0.0.0.0",
            "listen_port": 443,
            "sniff": true,
            "sniff_override_destination": true,
            "domain_strategy": "ipv4_only",
            "up_mbps": 20,
            "down_mbps": 200,
            "users": [
                {
                    "auth_str": "chika"
                }
            ],
            "recv_window_conn": 26843545,
            "recv_window_client": 67108864,
            "max_conn_client": 4096,
            "disable_mtu_discovery": false,
            "tls": {
                "enabled": true,
                "alpn": [
                    "h3"
                ],
                "certificate_path": "/root/ssl/cert.crt",
                "key_path": "/root/ssl/private.key"
            }
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
        },
        "rules": [
            {
                "geoip": [
                    "cn"
                ],
                "outbound": "block"
            }
        ]
    }
 }
  ```
<details><summary>客户端配置如下</summary> 

  ```
{
    "protocol": "udp",
    "server": "wodeip:443",
    "server_name": "wodeyuming",
    "alpn": "h3",
    "up_mbps": 20,
    "down_mbps": 200,
    "auth_str": "riande",
    "socks5": {
        "listen": "127.0.0.1:50000"
    }
}

**Comment by chika0801** [comment]
客户端配置是hy的格式，你用hy的.exe执行下了。

一般我是v2rayn加自定义配置（这个自定义配置是hy的模式）

https://github.com/chika0801/sing-box-install#v2rayn%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97

下载Windows客户端程序[hysteria-windows-amd64.exe](https://github.com/HyNetwork/hysteria/releases/latest/download/hysteria-windows-amd64.exe)，重命令为hysteria.exe，复制到v2rayN文件夹。

下载客户端配置[config_client.json](https://github.com/chika0801/sing-box-install/blob/main/hysteria/config_client.json)，修改chika.example.com为证书中包含的域名，修改10.0.0.1为VPS的IP。

服务器 ——> 添加自定义配置服务器 ——> 浏览(B) ——> 选择客户端配置 ——> Core类型 hysteria ——> Socks端口 50000

这儿下的客户端程序是hy的.exe

**Comment by rianjskis** [comment]
> 客户端配置是hy的格式，你用hy的.exe执行下了。
> 
> 一般我是v2rayn加自定义配置（这个自定义配置是hy的模式）
> 
> [https://github.com/chika0801/sing-box-install#v2rayn%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97 ](https://github.com/chika0801/sing-box-install#v2rayn%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97)
> 
> 下载Windows客户端程序 [hysteria-windows-amd64.exe ](https://github.com/HyNetwork/hysteria/releases/latest/download/hysteria-windows-amd64.exe)，重命令为hysteria.exe，复制到v2rayN文件夹。
> 
> 下载客户端配置 [config_client.json ](https://github.com/chika0801/sing-box-install/blob/main/hysteria/config_client.json)，修改chika.example.com为证书中包含的域名，修改10.0.0.1为VPS的IP。
> 
> 服务器 ——> 添加自定义配置服务器 ——> 浏览(B) ——> 选择客户端配置 ——> Core类型 hysteria ——> Socks端口 50000
> 
> 这儿下的客户端程序是hy的.exe

使用同上配置下载hy客户端后可以在本地的windows powerShell中 client运行成功,然后在用v2ray添加socks5运行成功,但是这样的话我不能关闭windows PowerShell关闭就会停止代理,尝试过下载hy到v2rayN文件夹,在添加自定义配置中选择了hy内核然后测速节点提示截图表达
![1](https://user-images.githubusercontent.com/86937445/204718654-fc838cc0-3e1b-406c-a729-4e132c24baa8.png)
![2](https://user-images.githubusercontent.com/86937445/204718669-570acea4-766b-4d0b-91c8-1fd27c5ac355.png)

![3](https://user-images.githubusercontent.com/86937445/204718681-1215e9a7-0662-4eab-9734-0b479315dfe8.png)

**Comment by chika0801** [comment]
正常情况是你在windows powerShell不运行hy

和你图上一样把hy.exe放到v2rayn文件夹里，看你自定义设置的图，也没设置错

你v2rayn选择这个自定义配置加载后，你浏览器打得开谷歌之类吗？

**Comment by rianjskis** [comment]
> 正常情况是你在windows powerShell不运行hy
> 
> 和你图上一样把hy.exe放到v2rayn文件夹里，看你自定义设置的图，也没设置错
> 
> 你v2rayn选择这个自定义配置加载后，你浏览器打得开谷歌之类吗？
> 
> 正常这么操作了，都是行的通的。

我使用的v2ray是5.28版本,加载后无法打开谷歌联网,也ping不通,
![屏幕截图 2022-11-30 143014](https://user-images.githubusercontent.com/86937445/204724563-18727e89-8b8d-4006-9a89-8efbe5ec1c40.png)
服务端看运行是正常的

**Comment by rianjskis** [comment]
> 正常情况是你在windows powerShell不运行hy
> 
> 和你图上一样把hy.exe放到v2rayn文件夹里，看你自定义设置的图，也没设置错
> 
> 你v2rayn选择这个自定义配置加载后，你浏览器打得开谷歌之类吗？
> 
> 正常这么操作了，都是行的通的。

搞定了大佬，原来是我把hy客户端丢v2ray文件夹里的名字多加了个.exe导致v2ray没找到这个内核所以没网,我改了下就连上了,哈哈哈,  请问我如上的服务端配置,如果用sing-box客户端启动,需要把出入站那些加上去吗,还是说只要服务端配置写好了出入站,客户端就不用写了.

**Comment by chika0801** [comment]
> 请问我如上的服务端配置,如果用sing-box客户端启动,需要把出入站那些加上去吗,还是说只要服务端配置写好了出入站,客户端就不用写了.

这段话我没听懂，你说详细点了

**Comment by rianjskis** [comment]
> > 请问我如上的服务端配置,如果用sing-box客户端启动,需要把出入站那些加上去吗,还是说只要服务端配置写好了出入站,客户端就不用写了.
> 
> 这段话我没听懂，你说详细点了



> > 请问我如上的服务端配置,如果用sing-box客户端启动,需要把出入站那些加上去吗,还是说只要服务端配置写好了出入站,客户端就不用写了.
> 
> 这段话我没听懂，你说详细点了

<details><summary>客户端</summary>
  ``` 
 要不要在客户端加上这些 因为刚尝试上面的您发的配置全局模式依然可以访问知乎B站
  ```
  ```
 "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        }
    ],
    "route": {
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db"
        },
        "rules": [
            {
                "geoip": [
                    "cn"
                ],
                "outbound": "block"
            }
        ]

**Comment by rianjskis** [comment]
我可以使用clashmeta能跑这个直接规则分流，似乎不太需要在客户端上加这些来限制了，感谢您的帮助，这个问题已经解决。

**Comment by chika0801** [comment]
> 要不要在客户端加上这些 因为刚尝试上面的您发的配置全局模式依然可以访问知乎B站

我用的是v2rayn ，里面的路由规则 我设置好了 CN IP 直连的。

比如你的机给朋友用，你不能保证他们都不会乱搞客户端APP设置，怕他们搞成全局代理。

你就在服务器端配置加上 阻止 CN IP。你无所谓，在服务器上面不加这规则也行。

**Comment by rianjskis** [comment]
> > 要不要在客户端加上这些 因为刚尝试上面的您发的配置全局模式依然可以访问知乎B站
> 
> 我用的是v2rayn ，里面的路由规则 我设置好了 CN IP 直连的。
> 
> 比如你的机给朋友用，你不能保证他们都不会乱搞客户端APP设置，怕他们搞成全局代理。
> 
> 你就在服务器端配置加上 阻止 CN IP。你无所谓，在服务器上面不加这规则也行。

言之有理，所以还是在服务端配置禁用cn ip 最佳

**Comment by chika0801** [comment]
> 言之有理，所以还是在服务端配置禁用cn ip 最佳

我现在想通的，就是这个作用，不管是在VPS阻止访问CN iP，还是把 CN IP给WARP。

你不信了不加也没事。

重要的是用的协议组合，现在就VISION，HY TUIC，我都没用VISION了，个人的机都是HY TUIC。

xxx TCP TLS 或 VISION，是给朋友用的机，帮他们配的，拿他们用。

**Comment by rianjskis** [comment]
> > 言之有理，所以还是在服务端配置禁用cn ip 最佳
> 
> 我现在想通的，就是这个作用，不管是在VPS阻止访问CN iP，还是把 CN IP给WARP。
> 
> 你不信了不加也没事。
> 
> 重要的是用的协议组合，现在就VISION，HY TUIC，我都没用VISION了，个人的机都是HY TUIC。
> 
> 开 xxx TCP TLS 或 VISION 协议组合，是在给朋友用的机上开的，给他们用。

必须信，已经加上了禁止cn ip哈哈哈， 请问搭载hy协议后,有nginx的反代示例吗,想做个小伪装,哈哈哈.
大佬,你的tuic也是用的sing-box搭建的吗,

**Comment by chika0801** [comment]
>  请问搭载hy协议后,有nginx的反代示例吗,想做个小伪装,

搭hy和你安nginx没关联，比如你这机开了Hy，你再想建个BLOG或开什么你正常搞就是了。

我建议翻墙机就翻墙，其它都不装就是了


> 你的tuic也是用的sing-box搭建

TUIC只能用TUIC自己程序配。是HY除了Hy原版，Sing-box也支持了HY

**Comment by rianjskis** [comment]
> > 请问搭载hy协议后,有nginx的反代示例吗,想做个小伪装,
> 
> 搭hy和你安nginx没关联，比如你这机开了Hy，你再想建个BLOG或开什么你正常搞就是了。
> 
> 我建议翻墙机就翻墙，其它都不装就是了
> 
> > 你的tuic也是用的sing-box搭建
> 
> TUIC只能用TUIC自己程序配。是HY除了Hy原版，Sing-box也支持了HY

刚看了您的其他仓库发现了，tuic也是个单独项目跟用户端，
以后在学习tuic,今天在大佬指点下学会了sing-box,哈哈哈,满足了.刚尝试改了改之前您的xray的nginx反代配置,丢进去发现不太行没成功反代,哈哈哈,
<details><summary>nginx配置</summary>
user nginx;
worker_processes auto;

error_log /root/xray+nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}


http {
    log_format main '[$time_local] $proxy_protocol_addr:$proxy_protocol_port "$request" "$http_referer" "$http_user_agent"';
    access_log /root/xray+nginx/access.log main;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        set_real_ip_from 127.0.0.1;
        real_ip_header proxy_protocol;
        
           location / {
            resolver 1.1.1.1;
            proxy_pass https://www.lovelive-anime.jp; #伪装网址
            proxy_redirect off;
            proxy_ssl_server_name on;
            sub_filter_once off;
            sub_filter "lovelive-anime.jp" $server_name;
            proxy_set_header Host "lovelive-anime.jp";
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Accept-Language "zh-CN";
            }
     }
}

**Comment by chika0801** [comment]
nginx反代其它网站我都没再深入学习，当时搞个反代纯为了自己好看点，现在也不需要了。
