### ISSUE TITLE
please add sing-box to  vmess+ws+tsl+cdn server config file

### ISSUE THREAD

**Issue by zhe1253** [chika0801/sing-box-install#8]
please add sing-box to  vmess+ws+tsl+cdn server config file.
i use NAT ipv6 vps install sing-box,
i think use vmess+ws+tsl  and cloudflare CDN,
but not find all config file.
please give an example of a config file

**Comment by chika0801** [comment]
我没有时间再写sing-box的 vmess+ws+tls配置文件。你可以用xray的配置文件 https://github.com/chika0801/Xray-examples/tree/main/VMess-WebSocket-TLS

nginx:443-> ws -> xray
