### ISSUE TITLE
Requests vless grpc reality client

### ISSUE THREAD

**Issue by malikshi** [chika0801/sing-box-install#9]
add VLESS-gRPC-uTLS-REALITY client. i try to setup client transport grpc without servicename and won't work!

**Comment by chika0801** [comment]
这是使用Xray-core作为客户端的配置文件

https://github.com/chika0801/Xray-examples/blob/main/VLESS-gRPC-uTLS-REALITY/config_client.json

如果你使用REALITY，客户端和服务端配置里的servicename参数，是必填项目。

请参考https://github.com/XTLS/REALITY关于配置参数的说明。

**Comment by chika0801** [comment]
https://github.com/chika0801/sing-box-install/commit/399d4e95a5d65fcf2eabc4b0f7f3471707bfa611

这是一个使用sing-box作为客户端的配置文件示例

**Comment by malikshi** [comment]
> [399d4e9](https://github.com/chika0801/sing-box-install/commit/399d4e95a5d65fcf2eabc4b0f7f3471707bfa611)
> 
> 这是一个使用sing-box作为客户端的配置文件示例

last night i already tried these, with and without service_name, the result not working at all. maybe i will give a try again later

```
            "transport": {
                "type": "grpc"
            }
```
